import React from "react";
import Head from "next/head";

import Main from "./main";
import Contact from "./contact";
import contact from "./contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {Main()}
      {Contact()}
    </div>
  );
}
