import React from "react";
import Head from "next/head";
import dpsection2 from "../public/dev-img01.png";

import Main from "./main";
import Contact from "./contact";
import contact from "./contact";
import NavBar from "../pages/layout/Navbar";
import Service from "../pages/Services";
import Portfolio from "./Portfolio";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {NavBar()}
      {Main()}
      {Service()}
      {Portfolio()}
      {Contact()}
    </div>
  );
}
